
                local record = {
                    x = -32,
                    y = 0,
                    z = -8,
                    blue_print = true,
                    name = "【预设】六锅",
                    data = {{
            x = -35.031089782715,
            y = 0,
            z = -9.75,
            layer = 6,
            rotation = -90,
            name = "烹饪锅",
            anim = "idle_empty",
            bank = "cook_pot",
            prefab = "cookpot",
            build = "cookpot_survival",
            scale = {1, 1, 1}
        },{
            x = -33.5,
            y = 0,
            z = -9.5,
            layer = 6,
            rotation = -90,
            name = "盐盒",
            anim = "closed",
            bank = "saltbox",
            prefab = "saltbox",
            build = "saltbox_shaker",
            scale = {1, 1, 1}
        },{
            x = -28.968910217285,
            y = 0,
            z = -9.75,
            layer = 6,
            rotation = -90,
            name = "烹饪锅",
            anim = "idle_empty",
            bank = "cook_pot",
            prefab = "cookpot",
            build = "cookpot_survival",
            scale = {1, 1, 1}
        },{
            x = -33.5,
            y = 0,
            z = -8,
            layer = 6,
            rotation = -90,
            name = "冰箱",
            anim = "closed",
            bank = "icebox",
            prefab = "icebox",
            build = "icebox_crystal",
            scale = {1, 1, 1}
        },{
            x = -30.5,
            y = 0,
            z = -6.5,
            layer = 6,
            rotation = -90,
            name = "盐盒",
            anim = "closed",
            bank = "saltbox",
            prefab = "saltbox",
            build = "saltbox_shaker",
            scale = {1, 1, 1}
        },{
            x = -33.5,
            y = 0,
            z = -6.5,
            layer = 6,
            rotation = -90,
            name = "盐盒",
            anim = "closed",
            bank = "saltbox",
            prefab = "saltbox",
            build = "saltbox_shaker",
            scale = {1, 1, 1}
        },{
            x = -28.968910217285,
            y = 0,
            z = -6.25,
            layer = 6,
            rotation = -90,
            name = "烹饪锅",
            anim = "idle_empty",
            bank = "cook_pot",
            prefab = "cookpot",
            build = "cookpot_survival",
            scale = {1, 1, 1}
        },{
            x = -30.5,
            y = 0,
            z = -9.5,
            layer = 6,
            rotation = -90,
            name = "盐盒",
            anim = "closed",
            bank = "saltbox",
            prefab = "saltbox",
            build = "saltbox_shaker",
            scale = {1, 1, 1}
        },{
            x = -32,
            y = 0,
            z = -6.5,
            layer = 6,
            rotation = -90,
            name = "冰箱",
            anim = "closed",
            bank = "icebox",
            prefab = "icebox",
            build = "icebox_crystal",
            scale = {1, 1, 1}
        },{
            x = -30.5,
            y = 0,
            z = -8,
            layer = 6,
            rotation = -90,
            name = "冰箱",
            anim = "closed",
            bank = "icebox",
            prefab = "icebox",
            build = "icebox_crystal",
            scale = {1, 1, 1}
        },{
            x = -32,
            y = 0,
            z = -4.5,
            layer = 6,
            rotation = -90,
            name = "烹饪锅",
            anim = "idle_empty",
            bank = "cook_pot",
            prefab = "cookpot",
            build = "cookpot_survival",
            scale = {1, 1, 1}
        },{
            x = -32,
            y = 0,
            z = -8,
            layer = 6,
            rotation = -90,
            name = "盐盒",
            anim = "close",
            bank = "saltbox",
            prefab = "saltbox",
            build = "saltbox_shaker",
            scale = {1, 1, 1}
        },{
            x = -35.031089782715,
            y = 0,
            z = -6.25,
            layer = 6,
            rotation = -90,
            name = "烹饪锅",
            anim = "idle_empty",
            bank = "cook_pot",
            prefab = "cookpot",
            build = "cookpot_survival",
            scale = {1, 1, 1}
        },{
            x = -32,
            y = 0,
            z = -11.5,
            layer = 6,
            rotation = -90,
            name = "烹饪锅",
            anim = "idle_empty",
            bank = "cook_pot",
            prefab = "cookpot",
            build = "cookpot_survival",
            scale = {1, 1, 1}
        },{
            x = -32,
            y = 0,
            z = -9.5,
            layer = 6,
            rotation = -90,
            name = "冰箱",
            anim = "closed",
            bank = "icebox",
            prefab = "icebox",
            build = "icebox_crystal",
            scale = {1, 1, 1}
        },}
                };
                return record
            